name: deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.18.0]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Create .env file
              run: |
                pwd
                touch .env.production
                echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env.production
                echo GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} >> .env.production
                echo MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }} >> .env.production
                echo YOUTUBE_CLIENT_ID=${{ secrets.YOUTUBE_CLIENT_ID }} >> .env.production
                echo YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }} >> .env.production
                cat .env.production
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: ssh connect & production
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:latest
                  sudo docker stop ${{secrets.DOCKER_CONTAINER_NAME}}
                  sudo docker rm ${{secrets.DOCKER_CONTAINER_NAME}}
                  sudo docker run -d --restart on-failure --name ${{secrets.DOCKER_CONTAINER_NAME}} ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_NAME}}:latest

